version: '3.5'

services:
  api01: # API - Instância 01
    image: felipph/rinha-elixir-app 
    hostname: api01
    environment:
      - PORT=80
      - APP_NAME=API1
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  api02: # API - Instância 02
    image: felipph/rinha-elixir-app 
    hostname: api02
    environment:
      - PORT=80
      - APP_NAME=API2
    depends_on:
      - db
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
    volumes:
      - ./docker/db/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
networks:
  default:
    driver: bridge
    name: rinha