version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2GB'
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
  # nginx:
  #   image: bandolin/nginxrinhaapi_simplified:latest
  #   depends_on:
  #     - api1
  #     - api2
  #   ports:
  #     - '9999:9999'
  #   networks:
  #     - app-tier
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.2'
  #         memory: '0.2GB'
  # api1:
  #   image: bandolin/rinhabackend_simplified:latest
  #   depends_on:
  #     - mysql
  #     - redis
  #   networks:
  #     - app-tier
  #   expose:
  #     - "80"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.2'
  #         memory: '0.6GB'